# Generated by Django 5.1.6 on 2025-03-16 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfuel', models.CharField(choices=[('CNG', 'CNG'), ('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=50)),
                ('stransmission', models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto')], max_length=100)),
                ('cname', models.CharField(max_length=100)),
                ('milegae', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('luggage', models.IntegerField()),
                ('desc', models.TextField()),
                ('air', models.BooleanField(default=True)),
                ('gps', models.BooleanField(default=True)),
                ('leaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
