# Generated by Django 5.1.6 on 2025-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cimage',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
