# Generated by Django 5.1.6 on 2025-03-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_car_cimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
