# Generated by Django 5.1.6 on 2025-04-09 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='leaser',
            new_name='lessor',
        ),
        migrations.RemoveField(
            model_name='car',
            name='price',
        ),
        migrations.AddField(
            model_name='car',
            name='audioinput',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='bluetooth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='carkit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='childseat',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='climatecontrol',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='cprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='longtermtips',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='onboardcomputer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='remotecontrollocking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='seatbelt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='sleepingbed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='water',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='luggage',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='stransmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto')], max_length=50),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pickup_address', models.TextField()),
                ('drop_address', models.TextField()),
                ('pick_time', models.TimeField()),
                ('total_days', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='myapp.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
