# Generated by Django 5.1.6 on 2025-04-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_leaser_car_lessor_remove_car_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
