# Generated by Django 5.1.6 on 2025-04-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_user_password_alter_user_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='air',
        ),
        migrations.RemoveField(
            model_name='car',
            name='audioinput',
        ),
        migrations.RemoveField(
            model_name='car',
            name='bluetooth',
        ),
        migrations.RemoveField(
            model_name='car',
            name='carkit',
        ),
        migrations.RemoveField(
            model_name='car',
            name='childseat',
        ),
        migrations.RemoveField(
            model_name='car',
            name='climatecontrol',
        ),
        migrations.RemoveField(
            model_name='car',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='car',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='car',
            name='longtermtips',
        ),
        migrations.RemoveField(
            model_name='car',
            name='luggage',
        ),
        migrations.RemoveField(
            model_name='car',
            name='milegae',
        ),
        migrations.RemoveField(
            model_name='car',
            name='music',
        ),
        migrations.RemoveField(
            model_name='car',
            name='onboardcomputer',
        ),
        migrations.RemoveField(
            model_name='car',
            name='remotecontrollocking',
        ),
        migrations.RemoveField(
            model_name='car',
            name='seatbelt',
        ),
        migrations.RemoveField(
            model_name='car',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='car',
            name='sleepingbed',
        ),
        migrations.RemoveField(
            model_name='car',
            name='water',
        ),
    ]
